export const environment = {
    //Variables de entorno en desarrollo
    // urlBrand : 'http://localhost:8081/brands',
    // urlCategories : 'http://localhost:8081/categories',
    // urlCounties : 'http://localhost:8081/countries',
    // urlDeliveryStatus : 'http://localhost:8081/delivery',
    // urlLogin : 'http://localhost:8081/login',
    // urlMercadoPago : 'http://localhost:8081/create_preference',
    // urlOrder : 'http://localhost:8081/orders',
    // urlPassword : 'http://localhost:8081/recoverPassword',
    // urlProvinces : 'http://localhost:8081/provinces',
    // urlStatus : 'http://localhost:8081/status',
    // urlStocks : 'http://localhost:8081/stock',
    // urlSubCategories : 'http://localhost:8081/subCategories',
    // urlToys : 'http://localhost:8081/toys',
    // urlUsers : 'http://localhost:8081/users',

    // Variables de entorno en producción
    urlBrand : 'https://img-ciriu-tag.onrender.com/brands',
    urlCategories : 'https://img-ciriu-tag.onrender.com/categories',
    urlCounties : 'https://img-ciriu-tag.onrender.com/countries',
    urlDeliveryStatus : 'https://img-ciriu-tag.onrender.com/delivery',
    urlLogin : 'https://img-ciriu-tag.onrender.com/login',
    urlMercadoPago : 'https://img-ciriu-tag.onrender.com/create_preference',
    urlOrder : 'https://img-ciriu-tag.onrender.com/orders',
    urlPassword : 'https://img-ciriu-tag.onrender.com/recoverPassword',
    urlProvinces : 'https://img-ciriu-tag.onrender.com/provinces',
    urlStatus : 'https://img-ciriu-tag.onrender.com/status',
    urlStocks : 'https://img-ciriu-tag.onrender.com/stock',
    urlSubCategories : 'https://img-ciriu-tag.onrender.com/subCategories',
    urlToys : 'https://img-ciriu-tag.onrender.com/toys',
    urlUsers : 'https://img-ciriu-tag.onrender.com/users',
};