export const environment = {
    //Variables de entorno en desarrollo
    urlBrand : 'http://localhost:8081/brands',
    urlCategories : 'http://localhost:8081/categories',
    urlCounties : 'http://localhost:8081/countries',
    urlDeliveryStatus : 'http://localhost:8081/delivery',
    urlLogin : 'http://localhost:8081/login',
    urlMercadoPago : 'http://localhost:8081/create_preference',
    urlOrder : 'http://localhost:8081/orders',
    urlPassword : 'http://localhost:8081/recoverPassword',
    urlProvinces : 'http://localhost:8081/provinces',
    urlStatus : 'http://localhost:8081/status',
    urlStocks : 'http://localhost:8081/stock',
    urlSubCategories : 'http://localhost:8081/subCategories',
    urlToys : 'http://localhost:8081/toys',
    urlUsers : 'http://localhost:8081/users',

    // Variables de entorno en producción
    // urlBrand : 'https://backend-ciriu-production.up.railway.app/brands',
    // urlCategories : 'https://backend-ciriu-production.up.railway.app/categories',
    // urlCounties : 'https://backend-ciriu-production.up.railway.app/countries',
    // urlDeliveryStatus : 'https://backend-ciriu-production.up.railway.app/delivery',
    // urlLogin : 'https://backend-ciriu-production.up.railway.app/login',
    // urlMercadoPago : 'https://backend-ciriu-production.up.railway.app/create_preference',
    // urlOrder : 'https://backend-ciriu-production.up.railway.app/orders',
    // urlPassword : 'https://backend-ciriu-production.up.railway.app/recoverPassword',
    // urlProvinces : 'https://backend-ciriu-production.up.railway.app/provinces',
    // urlStatus : 'https://backend-ciriu-production.up.railway.app/status',
    // urlStocks : 'https://backend-ciriu-production.up.railway.app/stock',
    // urlSubCategories : 'https://backend-ciriu-production.up.railway.app/subCategories',
    // urlToys : 'https://backend-ciriu-production.up.railway.app/toys',
    // urlUsers : 'https://backend-ciriu-production.up.railway.app/users',
};